### ISSUE TITLE
Interop doesn't work between Java & Kotlin quick start apps

### ISSUE THREAD

**Issue by chalin** [grpc/grpc-kotlin#134]
If I run the Java quick start server and then the Kotlin quick start client, I'd expect them to work together, instead I get the following:

```console
# /git/lf/grpc-kotlin/examples (master)
$ ./build/install/examples/bin/hello-world-client
Exception in thread "main" io.grpc.StatusException: UNIMPLEMENTED: Method not found: io.grpc.examples.helloworld.Greeter/SayHello
        at io.grpc.Status.asException(Status.java:549)
        at io.grpc.kotlin.ClientCalls$rpcImpl$1$1$1.onClose(ClientCalls.kt:289)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
        at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:98)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
```

The is what I get when I run the Kotlin server and the Java client:

```console
# grpc-java-tmp-v1.30.1/examples (v1.30.1)
$ ./build/install/examples/bin/hello-world-client
Jun. 30, 2020 2:29:31 P.M. io.grpc.examples.helloworld.HelloWorldClient greet
INFO: Will try to greet world ...
Jun. 30, 2020 2:29:32 P.M. io.grpc.examples.helloworld.HelloWorldClient greet
WARNING: RPC failed: Status{code=UNIMPLEMENTED, description=Method not found: helloworld.Greeter/SayHello, cause=null}
```

**Comment by chalin** [comment]
This is because of the last round of changes I did (a while ago) to `hello_world.proto`. Will fall back to the "canonical" version of the file.
