### ISSUE TITLE
`ServerCalls.onHalfClose()` invokes `call.close()`

### ISSUE THREAD

**Issue by ikhoon** [grpc/grpc-kotlin#151]
After reading a request stream from a client completely, `ArmeriaServerCall` invokes `ServerCall.Listener.onHalfClose()`.
When `onHalfClose()` is called, the `rpcJob.invokeOnCompletion` in `kotlin.ServerCalls` calls `ServerCall.close()`.
That makes a request closed before receving a response correctly.
```java
	at com.linecorp.armeria.server.grpc.ArmeriaServerCall.close(ArmeriaServerCall.java:286)
	at io.grpc.kotlin.ServerCalls$serverCallListener$1.invoke(ServerCalls.kt:257)
	at io.grpc.kotlin.ServerCalls$serverCallListener$1.invoke(ServerCalls.kt:46)
	at kotlinx.coroutines.InvokeOnCompletion.invoke(JobSupport.kt:1386)
	at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1529)
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:323)
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:240)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:903)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:175)
	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:137)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:108)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:308)
	at kotlinx.coroutines.CancellableContinuationImpl.completeResume(CancellableContinuationImpl.kt:395)
	at kotlinx.coroutines.channels.AbstractChannel$ReceiveHasNext.resumeReceiveClosed(AbstractChannel.kt:913)
	at kotlinx.coroutines.channels.AbstractSendChannel.helpClose(AbstractChannel.kt:312)
	at kotlinx.coroutines.channels.AbstractSendChannel.close(AbstractChannel.kt:241)
	at kotlinx.coroutines.channels.SendChannel$DefaultImpls.close$default(Channel.kt:102)
	at io.grpc.kotlin.ServerCalls$serverCallListener$2.onHalfClose(ServerCalls.kt:288)
	at com.linecorp.armeria.server.grpc.ArmeriaServerCall.invokeHalfClose(ArmeriaServerCall.java:426)
	at com.linecorp.armeria.server.grpc.ArmeriaServerCall.endOfStream(ArmeriaServerCall.java:419)
```

JFYI: The upstream(gRPC-Java) `onHalfClose()` completes only `requestObserver`.
https://github.com/grpc/grpc-java/blob/9dc5eec4d76193334a37418db6114e7ae090d298/stub/src/main/java/io/grpc/stub/ServerCalls.java#L257-L261

**Comment by ikhoon** [comment]
I found another critical problem.
`SeverCalls.onHalfClose()` blocks Armeria's event loop until all requests are handled when the client sends 100 requests concurrently.
```java
15:20:59.746 [armeria-common-worker-nio-2-2] INFO c.l.a.server.grpc.ArmeriaServerCall - start invokeHalfClose
15:20:59.747 [armeria-common-blocking-tasks-1-26 @HelloService/ShortBlockingHello implementation#295] INFO  HelloServiceImpl - 93 Armeria
15:20:59.747 [armeria-common-blocking-tasks-1-51 @HelloService/ShortBlockingHello implementation#294] INFO  HelloServiceImpl - 92 Armeria
15:20:59.748 [armeria-common-blocking-tasks-1-52 @HelloService/ShortBlockingHello implementation#296] INFO  HelloServiceImpl - 94 Armeria
15:20:59.751 [armeria-common-blocking-tasks-1-13 @HelloService/ShortBlockingHello implementation#298] INFO  HelloServiceImpl - 96 Armeria
15:20:59.751 [armeria-common-blocking-tasks-1-12 @HelloService/ShortBlockingHello implementation#297] INFO  HelloServiceImpl - 95 Armeria
15:20:59.751 [armeria-common-blocking-tasks-1-53 @HelloService/ShortBlockingHello implementation#299] INFO  HelloServiceImpl - 97 Armeria
15:20:59.752 [armeria-common-worker-nio-2-2 @HelloService/ShortBlockingHello implementation#202] INFO  c.l.a.server.grpc.ArmeriaServerCall - close
15:20:59.753 [armeria-common-blocking-tasks-1-54 @HelloService/ShortBlockingHello implementation#300] INFO  HelloServiceImpl - 98 Armeria
15:20:59.754 [armeria-common-blocking-tasks-1-27 @HelloService/ShortBlockingHello implementation#301] INFO  HelloServiceImpl - 99 Armeria
15:20:59.763 [armeria-common-worker-nio-2-2] INFO  c.l.a.server.grpc.ArmeriaServerCall - finished invokeHalfClose
```

The log was added to the around `listener.onHalfClose()` like the following:
```
 private void invokeHalfClose() {
        try (SafeCloseable ignored = ctx.push()) {
            logger.info("start invokeHalfClose");
            listener.onHalfClose();
            logger.info("finished invokeHalfClose");
        } catch (Throwable t) {
            close(GrpcStatus.fromThrowable(t), new Metadata());
        }
    }
}
```
https://github.com/line/armeria/blob/master/grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java#L425

**Comment by lowasser** [comment]
I remain confused as to what the issue is and what's going on here, but let me attempt to walk through the logic:

The `rpcJob.invokeOnCompletion` runs only after `rpcJob` is complete, which passes the `requests` flow to the user's implementation, and then calls `call.sendMessage` on all responses.  Each call to `call.sendMessage` happens-before the call to `call.close`.

It could be a thread-safety issue, where `ServerCall` isn't truly done with `sendMessage` before `invokeOnCompletion` runs.  That would be...ugly.  We could try locking access to `call`, or running accesses to `call` in a single-threaded context, though where exactly that thread comes from would be awkward.

**Comment by lowasser** [comment]
To attempt to more directly address the initial reported issue: `ServerCall.Listener.onHalfClose()` marks the end of the requests flow.  That flow gets passed to the user's implementation, so what they do with it is up to them, but they are returning a flow (or writing a suspend function that gets turned into a singleton flow), and it's after the collection of that flow that `call.close` gets called.  So what happens after the requests flow ends should be up to the user's implementation.
