### ISSUE TITLE
Bad type on operand stack ('io/grpc/Metadata'  is not assignable to 'kotlin/jvm/internal/Ref$ObjectRef') (when unary call is made over inprocess channel)

### ISSUE THREAD

**Issue by mancini0** [grpc/grpc-kotlin#168]
I hit the following exception in a personal project, so I made a simpler repo  and was able to reproduce the issue.

I am running a test of a simple kotlin grpc service that responds with a greeting using the grpc-java inprocess facilities through grpcCleanupRule. I am using the master branch of grpc-kotlin, the project is built with Bazel.

To reproduce, run bazel test //hello-grpc:hello-service-test on the master branch of [this repo](https://github.com/mancini0/reproduce_grpc_kotlin_168)

```
kt_jvm_test(
    name="hello-service-test",
    srcs = ["src/test/kotlin/HelloServiceTest.kt"],
    test_class = "com.mancini.HelloServiceTest",
    deps=["@maven//:junit_junit",
          ":hello-service",
          "@maven//:com_google_truth_truth",
          "@io_grpc_grpc_java//testing"
        ]
)
```

Bad type on operand stack
Exception Details:
  Location:
    io/grpc/kotlin/ClientCalls.rpcImpl(Lio/grpc/Channel;Lio/grpc/MethodDescriptor;Lio/grpc/CallOptions;Lio/grpc/Metadata;Lio/grpc/kotlin/ClientCalls$Request;)Lkotlinx/coroutines/flow/Flow; @12: invokespecial
  Reason:
    Type 'io/grpc/Metadata' (current frame, stack[5]) is not assignable to 'kotlin/jvm/internal/Ref$ObjectRef'
  Current Frame:
    bci: @12
    flags: { }
    locals: { 'io/grpc/kotlin/ClientCalls', 'io/grpc/Channel', 'io/grpc/MethodDescriptor', 'io/grpc/CallOptions', 'io/grpc/Metadata', 'io/grpc/kotlin/ClientCalls$Request' }
    stack: { uninitialized 0, uninitialized 0, 'io/grpc/Channel', 'io/grpc/MethodDescriptor', 'io/grpc/CallOptions', 'io/grpc/Metadata', 'io/grpc/kotlin/ClientCalls$Request', null }
  Bytecode:
    0000000: bb00 dd59 2b2c 2d19 0419 0501 b700 e0c0
    0000010: 0077 b800 e6b0                         

java.lang.VerifyError: 
	at com.mancini.proto.hello.HelloGrpcKt$HelloCoroutineStub.sayHello(HelloOuterClassGrpcKt.kt:67)
	at com.mancini.HelloServiceTest$test$1.invokeSuspend(HelloServiceTest.kt:35)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.mancini.HelloServiceTest.test(HelloServiceTest.kt:34)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at io.grpc.testing.GrpcCleanupRule$1.evaluate(GrpcCleanupRule.java:125)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:108)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:116)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:159)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:85)
```

**Comment by mancini0** [comment]
I believe the "current frame ,stack[5]" refers to the Metadata() argument passed to the unaryRpc() generated method:

The GrpcClientStubGenerator calls the constructor of the Metadata() argument, and the Metadata argument imported under the alias of GrpcMetadata.


```
  unaryRpc(
      channel,
      HelloGrpc.getSayHelloMethod(),
      request,
      callOptions,
      Metadata()
    )


    val codeBlockMap = mapOf(
      "helperMethod" to helperMethod,
      "methodDescriptor" to method.descriptorCode,
      "parameter" to parameter,
      "headers" to GrpcMetadata::class
    )
...
    funSpecBuilder.addNamedCode(
      """
      return %helperMethod:M(
        channel,
        %methodDescriptor:L,
        %parameter:N,
        callOptions,
        %headers:T()
      )
```

**Comment by mancini0** [comment]
Closing as using the default version of kotlinx.coroutines included as a transative dep of this project (version 1.3.5) is not affected by this problem. (The test passes when I remove my explicit dependency on kotlinx.coroutines 1.3.8)

**Comment by nathanhleung** [comment]
I encountered the same issue with 1.4.1; using 1.3.5 instead fixed the issue

**Comment by jamesward** [comment]
@nathanhleung What version of Kotlin are you using?
