### ISSUE TITLE
 rpc method not implemented

### ISSUE THREAD

**Issue by DanteAndroid** [grpc/grpc-kotlin#309]
Hi, I followed the [tutorial](https://grpc.io/docs/platforms/android/kotlin/quickstart/) and encounter this error:
![image](https://user-images.githubusercontent.com/10005563/145919831-e52168fd-db27-4d11-98e2-923b995559ae.png)
I searched google and had no clue. Please help me!

**Comment by jamesward** [comment]
Did you make any changes to `HelloWorldServer.kt` ?

**Comment by TheHett** [comment]
Show you code

**Comment by DanteAndroid** [comment]
> Did you make any changes to `HelloWorldServer.kt` ?

I did change nothing, and I tried tiwce

**Comment by DanteAndroid** [comment]
> Show your code

I didn't change any code in the tutorial, which is https://github.com/grpc/grpc-kotlin

**Comment by jamesward** [comment]
With the server running, what happens when you run:
```
./gradlew :client:HelloWorldClient
```

**Comment by DanteAndroid** [comment]
> With the server running, what happens when you run:
> 
> ```
> ./gradlew :client:HelloWorldClient
> ```

```
Task :client:HelloWorldClient FAILED
Exception in thread "main" io.grpc.StatusException: UNIMPLEMENTED: RPC method not implemented /helloworld.Greeter/SayHello
        at io.grpc.Status.asException(Status.java:551)
        at io.grpc.kotlin.ClientCalls$rpcImpl$1$1$1.onClose(ClientCalls.kt:295)
        at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:463)
        at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:427)
        at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:460)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':client:HelloWorldClient'.
> Process 'command '/Users/l/Library/Java/JavaVirtualMachines/corretto-1.8.0_292/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s
12 actionable tasks: 1 executed, 11 up-to-date

```

**Comment by DanteAndroid** [comment]
PS: My JDK version is 16 then I met some Gradle error so I uninstall the jdk16, so my java version is 1.8 now (which may seem correlate to the error)

**Comment by jamesward** [comment]
Strange.  Can you paste the contents of `server/src/main/kotlin/io/grpc/examples/helloworld/HelloWorldServer.kt` here?

**Comment by DanteAndroid** [comment]
[HelloWorldServer.txt](https://github.com/grpc/grpc-kotlin/files/7731422/HelloWorldServer.txt)

**Comment by jamesward** [comment]
That looks right.  I'm pretty perplexed on what might be causing this.  Have you tried a clean? `./gradlew clean`

Also, I'm working on adding an integration test to our tests:
https://github.com/grpc/grpc-kotlin/pull/310

**Comment by DanteAndroid** [comment]
Hi, I'm focusing on my work right now so I'm gonna close this issue. But **if someone else met this issue, please comment below**.
