### ISSUE TITLE
Server stops responding to requests after coroutine cancellation when using thread pool executor

### ISSUE THREAD

**Issue by SanjayVas** [grpc/grpc-kotlin#353]
I updated my gRPC servers to use a fixed thread pool executor. I've noticed the server stops responding if the coroutine gets cancelled.

Stack trace:

```
java.util.concurrent.CancellationException: Cancellation received from client
        at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22)
        at kotlinx.coroutines.JobKt__JobKt.cancel(Job.kt:596)
        at kotlinx.coroutines.JobKt.cancel(Unknown Source)
        at kotlinx.coroutines.JobKt__JobKt.cancel$default(Job.kt:596)
        at kotlinx.coroutines.JobKt.cancel$default(Unknown Source)
        at io.grpc.kotlin.ServerCalls$serverCallListener$1.onCancel(ServerCalls.kt:275)
        at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40)
        at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closedInternal(ServerCallImpl.java:376)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:364)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:913)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

This was logged from a server interceptor that logs exceptions for debugging.

**Comment by SanjayVas** [comment]
Note that callers don't get an UNAVAILABLE. They just hang instead. My server interceptor doesn't log a request, so I suspect something is happening with the threads that handle incoming requests.

**Comment by SanjayVas** [comment]
Note that in my situation, I have one gRPC server that calls another.

I'm investigating whether this could be a different issue in another thread pool, as restarting the frontend server got the backend to start accepting requests. The error log was from the backend.

**Comment by SanjayVas** [comment]
Nevermind, I don't think that this is related to the cancellation error. I think something else ends up blocking all of my server threads, and the cancellation is just what happens to allow the next request to go through.

If this were in fact an issue, I imagine RPC deadlines just wouldn't work at all.
