### ISSUE TITLE
interop tests fails against java server

### ISSUE THREAD

**Issue by saturnism** [grpc/grpc-kotlin#37]
Interop fails w/ Kotlin Client vs Java Server:

```
# In grpc-java
./run-test-server.sh --use_tls=true

# In grpc-kotlin
./run-test-client.sh --server_host_override=foo.test.google.fr --use_test_ca=true --test_case=unimplemented_service
```

Or, Java Client vs Kotlin Server
```
# in grpc-kotlin
./run-test-server.sh --use_tls=true

# In grpc-java
./run-test-client.sh --server_host_override=foo.test.google.fr --use_test_ca=true --test_case=unimplemented_service
```

Kotlin client + Kotlin server passed though.

**Comment by saturnism** [comment]
fwiw, is tls is turned off, then all tests passes. (`--use_tls=false`)

or, from grpc interop test

```
tools/run_tests/run_interop_tests.py -l kotlin -s java --use_docker --transport_security=insecure
Seen --use_docker flag, will run interop tests under docker.

IMPORTANT: The changes you are testing need to be locally committed
because only the committed changes in the current branch will be
copied to the docker environment.
START: Building interop docker images.
PASSED: build_docker_kotlin [time=173.2sec, retries=0:0]
PASSED: build_docker_java [time=276.5sec, retries=0:0]
SUCCESS: All docker images built successfully.
START: interop_server_java
PASSED: cloud_to_cloud:kotlin:java_server:timeout_on_sleeping_server:insecure [time=5.7sec, retries=0:0]
PASSED: cloud_to_cloud:kotlin:java_server:cancel_after_begin:insecure [time=6.4sec, retries=0:0]
PASSED: cloud_to_cloud:kotlin:java_server:cancel_after_first_response:insecure [time=6.5sec, retries=0:0]
PASSED: cloud_to_cloud:kotlin:java_server:unimplemented_method:insecure [time=6.6sec, retries=0:0]
PASSED: cloud_to_cloud:kotlin:java_server:unimplemented_service:insecure [time=6.6sec, retries=0:0]
PASSED: cloud_to_cloud:kotlin:java_server:empty_stream:insecure [time=6.7sec, retries=0:0]
PASSED: cloud_to_cloud:kotlin:java_server:special_status_message:insecure [time=6.6sec, retries=0:0]
PASSED: cloud_to_cloud:kotlin:java_server:empty_unary:insecure [time=6.7sec, retries=0:0]
PASSED: cloud_to_cloud:kotlin:java_server:client_streaming:insecure [time=6.7sec, retries=0:0]
PASSED: cloud_to_cloud:kotlin:java_server:ping_pong:insecure [time=6.8sec, retries=0:0]
PASSED: cloud_to_cloud:kotlin:java_server:server_streaming:insecure [time=6.8sec, retries=0:0]
PASSED: cloud_to_cloud:kotlin:java_server:large_unary:insecure [time=6.8sec, retries=0:0]
PASSED: cloud_to_cloud:kotlin:java_server:status_code_and_message:insecure [time=6.8sec, retries=0:0]
PASSED: cloud_to_cloud:kotlin:java_server:custom_metadata:insecure [time=6.8sec, retries=0:0]
PASSED: cloud_to_cloud:kotlin:java_server:server_compressed_unary:insecure [time=6.8sec, retries=0:0]
SUCCESS: All tests passed
Removing docker image grpc_interop_kotlin:42645023-552e-41d0-b59f-028cdd8778b8
Removing docker image grpc_interop_java:b5713053-14ba-4ca3-89a1-44b29b964101
```

**Comment by jtattermusch** [comment]
Note that the ca.pem, server.pem etc. were updated very recently in grpc-java (and in all other repos).
https://github.com/grpc/grpc-java/pull/6841/files

Could that be the reason why tests are failing?

**Comment by saturnism** [comment]
ah, got it.. i think that's definitely it... `grpc-java` master branch has the new cert, but `grpc-kotlin` is referring to `grpc-testing:1.26.0` which has the old cert.  `grpc` interop tests uses `../grpc-java` directory to build the container.

it looks like `grpc-java:1.28` is the latest release, and its `grpc-testing` artifact is still using the old cert as well.

as a workaround, test against older `grpc-java` tag:

in `grpc-java` directory:
```
git checkout v1.26.0
./gradlew :grpc-interop-testing:installDist -PskipAndroid=true -PskipCodegen=true
./run-test-server.sh --use_tls=true
```

The client client can connect without TLS issues.

Local `grpc` interop tests are also passing:
```
tools/run_tests/run_interop_tests.py -l kotlin -s java --use_docker                  system
Seen --use_docker flag, will run interop tests under docker.

IMPORTANT: The changes you are testing need to be locally committed
because only the committed changes in the current branch will be
copied to the docker environment.
START: Building interop docker images.
PASSED: build_docker_kotlin [time=137.9sec, retries=0:0]
PASSED: build_docker_java [time=180.4sec, retries=0:0]
SUCCESS: All docker images built successfully.
START: interop_server_java
PASSED: cloud_to_cloud:kotlin:java_server:timeout_on_sleeping_server:tls [time=5.4sec, retries=0:0]
PASSED: cloud_to_cloud:kotlin:java_server:cancel_after_begin:tls [time=7.3sec, retries=0:0]
PASSED: cloud_to_cloud:kotlin:java_server:cancel_after_first_response:tls [time=7.3sec, retries=0:0]
PASSED: cloud_to_cloud:kotlin:java_server:empty_stream:tls [time=7.5sec, retries=0:0]
PASSED: cloud_to_cloud:kotlin:java_server:unimplemented_method:tls [time=7.5sec, retries=0:0]
PASSED: cloud_to_cloud:kotlin:java_server:client_streaming:tls [time=7.6sec, retries=0:0]
PASSED: cloud_to_cloud:kotlin:java_server:special_status_message:tls [time=7.5sec, retries=0:0]
PASSED: cloud_to_cloud:kotlin:java_server:empty_unary:tls [time=7.6sec, retries=0:0]
PASSED: cloud_to_cloud:kotlin:java_server:ping_pong:tls [time=7.6sec, retries=0:0]
PASSED: cloud_to_cloud:kotlin:java_server:unimplemented_service:tls [time=7.6sec, retries=0:0]
PASSED: cloud_to_cloud:kotlin:java_server:status_code_and_message:tls [time=7.6sec, retries=0:0]
PASSED: cloud_to_cloud:kotlin:java_server:server_streaming:tls [time=7.7sec, retries=0:0]
PASSED: cloud_to_cloud:kotlin:java_server:large_unary:tls [time=7.7sec, retries=0:0]
PASSED: cloud_to_cloud:kotlin:java_server:server_compressed_unary:tls [time=7.7sec, retries=0:0]
PASSED: cloud_to_cloud:kotlin:java_server:custom_metadata:tls [time=7.7sec, retries=0:0]
SUCCESS: All tests passed
Removing docker image grpc_interop_kotlin:0432bcb8-2891-4666-92e3-bbef32c20f01
Removing docker image grpc_interop_java:9e1d307f-31a8-4175-9402-ef7395760708
```

```
tools/run_tests/run_interop_tests.py -l java -s kotlin --use_docker               3m 14s  system
Seen --use_docker flag, will run interop tests under docker.

IMPORTANT: The changes you are testing need to be locally committed
because only the committed changes in the current branch will be
copied to the docker environment.
START: Building interop docker images.
PASSED: build_docker_kotlin [time=134.8sec, retries=0:0]
PASSED: build_docker_java [time=163.6sec, retries=0:0]
SUCCESS: All docker images built successfully.
START: interop_server_kotlin
PASSED: cloud_to_cloud:java:kotlin_server:timeout_on_sleeping_server:tls [time=5.7sec, retries=0:0]
PASSED: cloud_to_cloud:java:kotlin_server:cancel_after_begin:tls [time=6.5sec, retries=0:0]
PASSED: cloud_to_cloud:java:kotlin_server:unimplemented_service:tls [time=7.5sec, retries=0:0]
PASSED: cloud_to_cloud:java:kotlin_server:empty_stream:tls [time=7.6sec, retries=0:0]
PASSED: cloud_to_cloud:java:kotlin_server:unimplemented_method:tls [time=7.5sec, retries=0:0]
PASSED: cloud_to_cloud:java:kotlin_server:empty_unary:tls [time=7.7sec, retries=0:0]
PASSED: cloud_to_cloud:java:kotlin_server:special_status_message:tls [time=7.6sec, retries=0:0]
PASSED: cloud_to_cloud:java:kotlin_server:server_streaming:tls [time=7.8sec, retries=0:0]
PASSED: cloud_to_cloud:java:kotlin_server:client_streaming:tls [time=7.8sec, retries=0:0]
PASSED: cloud_to_cloud:java:kotlin_server:status_code_and_message:tls [time=7.8sec, retries=0:0]
PASSED: cloud_to_cloud:java:kotlin_server:cancel_after_first_response:tls [time=7.8sec, retries=0:0]
PASSED: cloud_to_cloud:java:kotlin_server:ping_pong:tls [time=7.9sec, retries=0:0]
PASSED: cloud_to_cloud:java:kotlin_server:custom_metadata:tls [time=7.8sec, retries=0:0]
PASSED: cloud_to_cloud:java:kotlin_server:large_unary:tls [time=7.9sec, retries=0:0]
PASSED: cloud_to_cloud:java:kotlin_server:server_compressed_unary:tls [time=7.8sec, retries=0:0]
SUCCESS: All tests passed
Removing docker image grpc_interop_kotlin:4878321f-5e79-45e8-b05f-9b1ac79e624d
Removing docker image grpc_interop_java:87d6c96a-b603-480e-a98f-f11b9bb4df40
```

**Comment by saturnism** [comment]
> Btw, having wrong certificates is something that should be possible to tell from the test's error log ("failed handshake becuase XYZ"). What did the failed test print? Could that message be improved?

i didn't capture the highest error msg, but the root cause exception was something along the lines of
```
java.security.SignatureException: Signature length not correct: got ... but was expecting 128
```

**Comment by lowasser** [comment]
Hmmkay.  I don't think the grpc-kotlin repo has a copy of the certificates like there appears to be in grpc-java.  Just upgrading the version of grpc-java we're depending on causes a very odd 

```
Exception in thread "main" java.lang.NoSuchMethodError: io.grpc.netty.NettyChannelBuilder.getOffloadExecutorPool()Lio/grpc/internal/ObjectPool;
        at io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:403)
        at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:519)
        at io.grpc.testing.integration.TestServiceClient$Tester.createChannel(TestServiceClient.kt:288)
        at io.grpc.testing.integration.AbstractInteropTest.setUp(AbstractInteropTest.kt:240)
        at io.grpc.testing.integration.TestServiceClient.setUp(TestServiceClient.kt:150)
        at io.grpc.testing.integration.TestServiceClient$Companion.main(TestServiceClient.kt:304)
        at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.kt)
```

...which seems strange not least because it's Java gRPC on both sides and I'd've expected those, at least, to be in version sync?

**Comment by chalin** [comment]
I believe that interop tests are passing now, right?

**Comment by saturnism** [comment]
@lowasser the cert is pulled in from `grpc-testing`, and the interop test uses the new cert that's only published in the newer version of `grpc-testing`.

to upgrade, we need to upgrade all grpc-java modules.

**Comment by saturnism** [comment]
@chalin interop build seems broken; we still need #33 to run interop on open source.
