### ISSUE TITLE
Cannot connect server connection timed out

### ISSUE THREAD

**Issue by BekzodYusupov** [grpc/grpc-kotlin#431]
Cannot connect to the server. Timed out exception

```
val channel = ManagedChannelBuilder
                            .forAddress("api-dev.*-***.uz", ****) //for safety reasons cannot write real host && port
                            .build()

                        val request = AuthRequest.newBuilder()
                            .setUsername("user123")
                            .setPassword("user123")
                            .build()

                        val stubAuth = AuthServiceGrpcKt.AuthServiceCoroutineStub(channel)
                        val response = stubAuth.authenticate(request)//timed out after about 2 min
```

error:
`FATAL EXCEPTION: main
                                                                                                    Process: com.example.grpc, PID: 12108
                                                                                                    io.grpc.StatusException: UNAVAILABLE
                                                                                                      at io.grpc.Status.asException(Status.java:552)
                                                                                                      at io.grpc.kotlin.ClientCalls$rpcImpl$1$1$1.onClose(ClientCalls.kt:296)
                                                                                                      at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:567)
                                                                                                      at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:71)
                                                                                                      at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:735)
                                                                                                      at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:716)
                                                                                                      at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
                                                                                                      at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
                                                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                      at java.lang.Thread.run(Thread.java:1012)
                                                                                                      Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@73eb792, androidx.compose.runtime.BroadcastFrameClock@e8ed563, StandaloneCoroutine{Cancelling}@5673560, AndroidUiDispatcher@7752a19]
                                                                                                    Caused by: java.net.ConnectException: failed to connect to api-dev.*-***.uz/**.***.***.*** (port ****) from /:: (port *****): connect failed: ETIMEDOUT (Connection timed out)
                                                                                                      at libcore.io.IoBridge.connect(IoBridge.java:187)
                                                                                                      at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
                                                                                                      at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
                                                                                                      at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
                                                                                                      at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
                                                                                                      at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
                                                                                                      at java.net.Socket.connect(Socket.java:646)
at java.net.Socket.connect(Socket.java:595)
                                                                                                      at java.net.Socket.<init>(Socket.java:475)
                                                                                                      at java.net.Socket.<init>(Socket.java:275)
                                                                                                      at javax.net.DefaultSocketFactory.createSocket(SocketFactory.java:285)
                                                                                                      at io.grpc.okhttp.OkHttpClientTransport$3.run(OkHttpClientTransport.java:535)
                                                                                                      ... 4 more
                                                                                                    Caused by: android.system.ErrnoException: connect failed: ETIMEDOUT (Connection timed out)
                                                                                                      at libcore.io.Linux.connect(Native Method)
                                                                                                      at libcore.io.ForwardingOs.connect(ForwardingOs.java:201)
                                                                                                      at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:158)
                                                                                                      at libcore.io.ForwardingOs.connect(ForwardingOs.java:201)
                                                                                                      at libcore.io.IoBridge.connectErrno(IoBridge.java:201)
                                                                                                      at libcore.io.IoBridge.connect(IoBridge.java:179)
                                                                                                      ... 15 more`

**Comment by jamesward** [comment]
Any way you can create a reproducible project for this?

**Comment by BekzodYusupov** [comment]
> Any way you can create a reproducible project for this?

@jamesward port was wrong, sorry for disturbance. First time trying to implement gRPC, so there are lot of doubts.
