### ISSUE TITLE
Error building GRPC/protobuf with Gradle 8.3

### ISSUE THREAD

**Issue by EAGrahamJr** [grpc/grpc-kotlin#432]
I know keeping up with Gradle versions is tedious, but it's broken the plugin (again):

```
'org.gradle.api.NamedDomainObjectContainer org.gradle.kotlin.dsl.NamedDomainObjectContainerExtensionsKt.invoke(org.gradle.api.NamedDomainObjectContainer, kotlin.jvm.functions.Function1)'
```

When building with Gradle 7.6.2 the following message is output:
```
$ ./gradlew clean --warning-mode all --stacktrace
> Configure project :buildSrc
WARNING: Unsupported Kotlin plugin version.
The `embedded-kotlin` and `kotlin-dsl` plugins rely on features of Kotlin `1.7.10` that might work differently than in the requested version `1.9.0`.

> Configure project :api
Using method NamedDomainObjectContainer<T>.invoke(kotlin.Function1) has been deprecated. This is scheduled to be removed in Gradle 8.0. Recompile your plugin against Gradle >= 6.8 Consult the upgrading guide for further information: https://docs.gradle.org/7.6.2/userguide/upgrading_version_6.html#using_NamedDomainObjectContainer_invoke_kotlin_Function1
at org.gradle.kotlin.dsl.NamedDomainObjectContainerExtensionsKt.invoke(NamedDomainObjectContainerExtensions.kt:61)
at com.google.protobuf.gradle.KtDslCompatibilityUtils.configureNamedDomainObjectContainer(KtDslCompatibilityUtils.java:32)
at com.google.protobuf.gradle.ProtobufConfiguratorExtsKt$plugins$1.invoke(ProtobufConfiguratorExts.kt:123)
at com.google.protobuf.gradle.ProtobufConfiguratorExtsKt$plugins$1.invoke(ProtobufConfiguratorExts.kt)
at org.gradle.kotlin.dsl.KotlinClosure1.doCall(GroovyInteroperability.kt:94)
```

**Comment by jamesward** [comment]
I recently bumped the [examples](https://github.com/grpc/grpc-kotlin/tree/master/examples) to Gradle 8.3 so you can reference that.  I think maybe you need a newer `id("com.google.protobuf")` version.  Let me know if that works.

**Comment by EAGrahamJr** [comment]
Yes, a newer version of the protobuf plugin (`"0.9.4"`) fixed this. Copilot has not been my friend today...  :imp:
