### ISSUE TITLE
Server UNAVAILABLE

### ISSUE THREAD

**Issue by BekzodYusupov** [grpc/grpc-kotlin#502]
Is it possible to get error UNAVAILABLE? if port is wrong or maybe changed. Android app used to work perfectly, but now I have problem. if I check connection through POSTMAN there is no problem at all. But you actually don't have to write port when using POSTMAN. 

 error localizedMessage - UNAVAILABLE
 error cause - javax.net.ssl.SSLHandshakeException: Chain validation failed
 
 `FATAL EXCEPTION: main
                                                                                                    Process: com.kotlinbek.grpc_practice, PID: 11178
                                                                                                    io.grpc.StatusException: UNAVAILABLE
                                                                                                    	at io.grpc.Status.asException(Status.java:552)
                                                                                                    	at io.grpc.kotlin.ClientCalls$rpcImpl$1$1$1.onClose(ClientCalls.kt:296)
                                                                                                    	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:489)
                                                                                                    	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:453)
                                                                                                    	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:486)
                                                                                                    	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:567)
                                                                                                    	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:71)
                                                                                                    	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:735)
                                                                                                    	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:716)
                                                                                                    	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
                                                                                                    	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@50b6b62, androidx.compose.runtime.BroadcastFrameClock@60c4f3, StandaloneCoroutine{Cancelling}@c2815b0, AndroidUiDispatcher@9cd0c29]
                                                                                                    Caused by: javax.net.ssl.SSLHandshakeException: Chain validation failed
                                                                                                    	at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:356)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:896)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.-$$Nest$mprocessDataFromSocket(Unknown Source:0)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:236)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:218)
                                                                                                    	at io.grpc.okhttp.OkHttpProtocolNegotiator.negotiate(OkHttpProtocolNegotiator.java:100)
                                                                                                    	at io.grpc.okhttp.OkHttpProtocolNegotiator$AndroidNegotiator.negotiate(OkHttpProtocolNegotiator.java:218)
                                                                                                    	at io.grpc.okhttp.OkHttpTlsUpgrader.upgrade(OkHttpTlsUpgrader.java:63)
                                                                                                    	at io.grpc.okhttp.OkHttpClientTransport$3.run(OkHttpClientTransport.java:551)
                                                                                                    	... 4 more
                                                                                                    Caused by: java.security.cert.CertificateException: Chain validation failed
                                                                                                    	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:719)
                                                                                                    	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:549)
                                                                                                    	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:570)
                                                                                                    	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:615)
                                                                                                    	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:615)
                                                                                                    	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:505)
                                                                                                    	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:425)
                                                                                                    	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:353)
                                                                                                    	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
                                                                                                    	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:163)
2023-12-27 12:49:08.815 11178-11178 AndroidRuntime          com.kotlinbek.grpc_practice          E  	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:260)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1638)
                                                                                                    	at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
                                                                                                    	at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:568)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
                                                                                                    	... 15 more
                                                                                                    Caused by: java.security.cert.CertPathValidatorException: timestamp check failed
                                                                                                    	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
                                                                                                    	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:222)
                                                                                                    	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:140)
                                                                                                    	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
                                                                                                    	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:309)
                                                                                                    	at android.sec.enterprise.certificate.DelegatingCertPathValidator.engineValidate(DelegatingCertPathValidator.java:63)
                                                                                                    	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:309)
                                                                                                    	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:715)
                                                                                                    	... 31 more
                                                                                                    Caused by: java.security.cert.CertificateExpiredException: Certificate expired at Tue Dec 26 13:21:27 GMT+05:00 2023 (compared to Wed Dec 27 12:49:08 GMT+05:00 2023)
                                                                                                    	at com.android.org.conscrypt.OpenSSLX509Certificate.checkValidity(OpenSSLX509Certificate.java:269)
                                                                                                    	at sun.security.provider.certpath.BasicChecker.verifyTimestamp(BasicChecker.java:194)
                                                                                                    	at sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144)
                                                                                                    	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
                                                                                                    	... 38 more
2023-12-27 12:49:08.891 11178-11178 Process                 com.kotlinbek.grpc_practice          I  Sending signal. PID: 11178 SIG: 9
2023-12-27 12:49:09.152  1432-1474  WindowManager           system_server                        E  win=Window{7621991 u0 com.kotlinbek.grpc_practice/com.kotlinbek.grpc_practice.MainActivity EXITING} destroySurfaces: appStopped=false cleanupOnResume=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.ActivityRecord.destroySurfaces:6539 com.android.server.wm.ActivityRecord.destroySurfaces:6520 com.android.server.wm.WindowState.onExitAnimationDone:5995 com.android.server.wm.ActivityRecord$$ExternalSyntheticLambda10.accept:2 java.util.ArrayList.forEach:1528 com.android.server.wm.ActivityRecord.onAnimationFinished:8607 com.android.server.wm.ActivityRecord.postApplyAnimation:6252 
`

**Comment by BekzodYusupov** [comment]
client side is working in android kotlin project. There hasn't been any major changes in framework right? it is so weird that it suddenly stopped working.

**Comment by BekzodYusupov** [comment]
it can be because of CA certificate. Backend developers checking it. I will inform as soon as results available.

**Comment by BekzodYusupov** [comment]
yes it is indeed because of certificate expiration.! if you have same problems, hold your cup of coffee and relax let back guys fix problem :)
