### ISSUE TITLE
Duplicate protobuf classes (lite) 

### ISSUE THREAD

**Issue by alexiionescu** [grpc/grpc-kotlin#609]
Hi guys,

I am trying to build an Android project for a simple gRPC client. (server is on Python working fine with a Python client)
I have taken the examples 'stub-android' and 'protos' and put them into a latest Android Compose app template.

The issue I have is the protobuf is generating duplicate 'lite' classes (for all of them)
I tried first with protobuf version '3.25' then with latest '4.27'. Result is the same.
Project is public here [zb_sniffer](https://github.com/alexiionescu/zb_sniffer)

Thank you

```
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.protobuf.AbstractMessageLite found in modules protobuf-java-4.27.0.jar -> protobuf-java-4.27.0 (com.google.protobuf:protobuf-java:4.27.0) and protobuf-javalite-4.27.0.jar -> protobuf-javalite-4.27.0 (com.google.protobuf:protobuf-javalite:4.27.0)
     Duplicate class com.google.protobuf.AbstractMessageLite$Builder found in modules protobuf-java-4.27.0.jar -> protobuf-java-4.27.0 (com.google.protobuf:protobuf-java:4.27.0) and protobuf-javalite-4.27.0.jar -> protobuf-javalite-4.27.0 (com.google.protobuf:protobuf-javalite:4.27.0)
     Duplicate class com.google.protobuf.AbstractMessageLite$Builder$LimitedInputStream found in modules protobuf-java-4.27.0.jar -> protobuf-java-4.27.0 (com.google.protobuf:protobuf-java:4.27.0) and protobuf-javalite-4.27.0.jar -> protobuf-javalite-4.27.0 (com.google.protobuf:protobuf-javalite:4.27.0)
     Duplicate class com.google.protobuf.AbstractMessageLite$InternalOneOfEnum found in modules protobuf-java-4.27.0.jar -> protobuf-java-4.27.0 (com.google.protobuf:protobuf-java:4.27.0) and protobuf-javalite-4.27.0.jar -> protobuf-javalite-4.27.0 (com.google.protobuf:protobuf-javalite:4.27.0)
     Duplicate class com.google.protobuf.AbstractParser found in modules protobuf-java-4.27.0.jar -> protobuf-java-4.27.0 (com.google.protobuf:protobuf-java:4.27.0) and protobuf-javalite-4.27.0.jar -> protobuf-javalite-4.27.0 (com.google.protobuf:protobuf-javalite:4.27.0)
     Duplicate class com.google.protobuf.AbstractProtobufList found in modules protobuf-java-4.27.0.jar -> protobuf-java-4.27.0 (com.google.protobuf:protobuf-java:4.27.0) and protobuf-javalite-4.27.0.jar -> protobuf-javalite-4.27.0 (com.google.protobuf:protobuf-javalite:4.27.0)
     Duplicate class com.google.protobuf.AllocatedBuffer found in modules protobuf-java-4.27.0.jar -> protobuf-java-4.27.0 (com.google.protobuf:protobuf-java:4.27.0) and protobuf-javalite-4.27.0.jar -> protobuf-javalite-4.27.0 (com.google.protobuf:protobuf-javalite:4.27.0)
...
```

**Comment by alexiionescu** [comment]
I have fixed the duplicate class by analyzing dependencies. 
I have found I have used some non-lite libs in my grade build scripts.
Protobuf version should have been "3.25.1", this is used by the 'grpc-protobuf-lite' lib. So I set this too.

Now the next issue I have faced is **The :app:processDebugResources task failed.**

Gradle --scan result are below. This gives me no clue of what is wrong really.
```
A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
> Unable to make AAPT link command
  ERROR: AAPT:
  > Dependent features configured but no package ID was set.
Exception
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:processDebugResources'.	
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:148)	
•••
Caused by: org.gradle.workers.internal.DefaultWorkerExecutor$WorkExecutionException: A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction	
at org.gradle.workers.internal.DefaultWorkerExecutor$WorkItemExecution.waitForCompletion(DefaultWorkerExecutor.java:283)	
•••
Caused by: com.android.builder.internal.aapt.v2.Aapt2Exception: Unable to make AAPT link command	
ERROR: AAPT: 	
at com.android.builder.internal.aapt.v2.Aapt2Exception$Companion.create(Aapt2Exception.kt:45)	
•••
at com.android.build.gradle.internal.res.Aapt2ErrorUtils.rewriteException(Aapt2ErrorUtils.kt:262)	
at com.android.build.gradle.internal.res.Aapt2ErrorUtils.rewriteLinkException(Aapt2ErrorUtils.kt:133)	
at com.android.build.gradle.internal.res.Aapt2ProcessResourcesRunnableKt.processResources(Aapt2ProcessResourcesRunnable.kt:76)	
at com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$Companion.invokeAaptForSplit(LinkApplicationAndroidResourcesTask.kt:941)	
at com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$Companion.access$invokeAaptForSplit(LinkApplicationAndroidResourcesTask.kt:796)	
at com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction.run(LinkApplicationAndroidResourcesTask.kt:432)	
at com.android.build.gradle.internal.profile.ProfileAwareWorkAction.execute(ProfileAwareWorkAction.kt:74)	
•••
Caused by: com.android.builder.internal.aapt.AaptException: Dependent features configured but no package ID was set.	
at com.android.builder.internal.aapt.v2.AaptV2CommandBuilder.makeLinkCommand(AaptV2CommandBuilder.kt:316)	
•••
at com.android.build.gradle.internal.services.PartialInProcessResourceProcessor.link(PartialInProcessResourceProcessor.kt:51)	
at com.android.build.gradle.internal.res.Aapt2ProcessResourcesRunnableKt.processResources(Aapt2ProcessResourcesRunnable.kt:74)	
at com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$Companion.invokeAaptForSplit(LinkApplicationAndroidResourcesTask.kt:941)	
at com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$Companion.access$invokeAaptForSplit(LinkApplicationAndroidResourcesTask.kt:796)	
at com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction.run(LinkApplicationAndroidResourcesTask.kt:432)	
at com.android.build.gradle.internal.profile.ProfileAwareWorkAction.execute(ProfileAwareWorkAction.kt:74)	
•••
```

**Comment by alexiionescu** [comment]
I found the issue. my 'stub-protos' project was configured as an android app instead of library.
Not related to graph
Now working. I will leave the example public for anyone who wants to not struggle like I did.
Also I did update everything to latest version grpc:1.64.0 and protobuf:4.27.0
